apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp-ingress
  namespace: chatapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: chatapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  number: 8000
          - path: /api/go
            pathType: Prefix
            backend:
              service:
                name: go-service
                port:
                  number: 8080
          - path: /api/java
            pathType: Prefix
            backend:
              service:
                name: java-service
                port:
                  number: 8090
          - path: /api/python
            pathType: Prefix
            backend:
              service:
                name: python-service
                port:
                  number: 8088
