apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatapp

resources:
  - namespace.yaml
  - zookeeper-deployment.yaml
  - kafka-deployment.yaml
  - python-service-deployment.yaml
  - java-service-deployment.yaml
  - go-service-deployment.yaml
  - ui-deployment.yaml
  - ingress.yaml
